### ISSUE TITLE
Create test plan

### ISSUE THREAD

**Issue by knowittobias** [knowitrickard/FlexiCharge-Test-and-integration#2]
Come up with a plan on what and how to test it. Alex can support with this.

**Comment by Khonin** [comment]
- [ ] Set up goals to reach
- [ ] Set up steps to reach the goals
- [ ] set up tasks to complete the steps

**Comment by Khonin** [comment]
I've created some drafts in the project backlog with the hierarchy looking something like this

## Goals
### - Create automated GitHub workflows for all team repositories. The goal with these workflows would be to automatically test the code comitted is working properly with the backend before it gets merged to production.
### - Well documented Readme. Containing not only how to run our tests locally but also on github Workflows. As well as examples of how to use our tests and how to create new tests.


In order to reach these goals we want to take these steps:
# Steps
### - Create small tests that evolve over time
### - Create workflows in the teams GitHub repositories now in the beginning of the project. So that we can implemented the small tests mentioned above and evolve them with the help of respective team.
### - Living documentation. We want to update our readme and code comments during the course of our sprints.

And we have broken down the steps into some tasks that we can more easily distrubute among ourselves as a group

# Tasks
## Send & Receive data via the REST API
###     - Write basic tests that confirms expected data
###     - Implement these tests in the repective repository workflow
## Send & Receive Expected data via the charger/backend websockets
###     - Write basic tests that confirms expected data
###     - Implement these tests in the repective repository workflow
## Create & extract data to and from the database
### - Implement tests for this in the backend repository

**Comment by Khonin** [comment]
Do you have any input on our current plan @knowittobias ?
